### ISSUE TITLE
elapsedTime 

### ISSUE THREAD

**Issue by maryamaffinityclick** [konoma/fps-counter#10]
this looks good but I was wondering why you didn't use
`elapsedTime = displayLink.duration`
instead of calculating `lastNotificationTime` and the `CFAbsoluteTimeGetCurrent` ... !
the object `CADisplayLink` already has the same thing.

 see here : https://developer.apple.com/documentation/quartzcore/cadisplaylink  

```The duration property provides the amount of time between frames at the maximumFramesPerSecond. To calculate the actual frame duration, use targetTimestamp - timestamp.```

**Comment by maryamaffinityclick** [comment]
actually I saw `displayLink.frameInterval` for the number of frames. which I think its the one we want instead of `numberOfFrames`  .
but based on these variables I'm getting almost 60 most of the time, but with your calculations Im getting very low rates. what do you think ?

**Comment by frenetisch-applaudierend** [comment]
Hi Mary

Thanks for your input.

I didn't know those properties, but reading the documentation I'm not 100% sure it matches what we need. The closest seems to be from the part you quoted: `elapsedTime = displayLink.targetTimestamp - displayLink.timestamp` However judging from the documentation and the behaviour you observe this seems to calculate the target frame duration (which for most apps will always be around 16.6ms => 60fps) not the actual duration that single frame took (which can be longer and if so will result in dropped frames).

If you still want to try it, I would suggest you test with the contained sample app, specifically with the table view app that has intentionally low frame rates. If you still get close to 60fps there, then it most likely is not what we need.
