### ISSUE TITLE
Shows counter on top of StatusBar

### ISSUE THREAD

**Issue by NuVeS** [konoma/fps-counter#15]
Shows counter on top of StatusBar instead of hiding it.
iOS 13.6

**Comment by frenetisch-applaudierend** [comment]
Hi NuVeS

Thank you for the issue report. However I need a little more description to your problem: What action have you performed? What did you expect? What happened instead?

Thanks!

**Comment by frenetisch-applaudierend** [comment]
I'm closing this as it seems that your problem has been solved. If not feel free to supply additional information.
