### ISSUE TITLE
Add new features:

### ISSUE THREAD

**Issue by DamnBoi706** [konoma/fps-counter#18]
is is possible to add cpu/gpu load/temp and ram usage? Bc That would be great! Also your tweak work great! Thank for your effort!

**Comment by frenetisch-applaudierend** [comment]
Hi, thank you for your interest and kind words!

That functionality is not planned currently, and I don't think I will support it in the future, as this tool is just intended to give a simple indicator of ui performance issues.

I would recommend to use the tools provided by Xcode and Instruments to get what you want, they are quite powerful and should provide what you look for.

Cheers!
