### ISSUE TITLE
how to use in objective-c?

### ISSUE THREAD

**Issue by fabiosoft** [konoma/fps-counter#5]
I imported the header but Xcode give me error. 

`FPSCounter must be imported from module FPSCounter.Swift before it is required`

**Comment by frenetisch-applaudierend** [comment]
Version 2.1.0 was just published which should address your issue

**Comment by Saahiljeet-Singh** [comment]
@fabiosoft  : Are you able to use it with your Objective C project, as I am still facing some issues.
I am getting this error " Use of undeclared identifier 'FPSCounter' ".

**Comment by MojtabaHs** [comment]
Try to build (command + B) after installing new pods (before importing and start usingthrm). Sometimes Xcode needs some compiling help
